services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
